const num = (k: string, d: number) => Number(process.env[k] ?? d);

export const thresholds = {
  credit: {
    IG_HY_SPREAD_2W_DELTA_BPS: num('IG_HY_SPREAD_2W_DELTA_BPS', 50),
    CC_DELINQ_90D_THRESHOLD: num('CC_DELINQ_90D_THRESHOLD', 14.0),
    HY_OAS_SPIKE_BPS: num('HY_OAS_SPIKE_BPS', 100)
  },
  energy: {
    PJM_LMP_THRESHOLD_USD_MWH: num('PJM_LMP_THRESHOLD_USD_MWH', 80),
    ERCOT_LMP_THRESHOLD_USD_MWH: num('ERCOT_LMP_THRESHOLD_USD_MWH', 80),
    CAISO_LMP_THRESHOLD_USD_MWH: num('CAISO_LMP_THRESHOLD_USD_MWH', 100)
  },
  cloud: {
    AWS_GROWTH_THRESHOLD_PCT: num('AWS_GROWTH_THRESHOLD_PCT', 20),
    AZURE_GROWTH_THRESHOLD_PCT: num('AZURE_GROWTH_THRESHOLD_PCT', 28),
    GCP_GROWTH_THRESHOLD_PCT: num('GCP_GROWTH_THRESHOLD_PCT', 30),
    CONCENTRATION_DELTA_PCT: 5
  }
};
